### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by KES777** [PerlFFI/FFI-Platypus#294]
[At this section](
https://metacpan.org/pod/FFI::Platypus#libuuid) `sizeof` is metioned, but at example values are just hardcoded

Could it be possible to use `sizeof` at example?

**Comment by plicease** [comment]
Agree.  That is confusing.  I think `sizeof` was used previously and the example got refactored, but it is a good place to use it in the example.

**Comment by plicease** [comment]
Fixed in #300
