### ISSUE TITLE
Unable to detect ffi_abis on macos arm64

### ISSUE THREAD

**Issue by plicease** [PerlFFI/FFI-Platypus#370]
```
*** Unable to detect ffi_abis     ***
[[[ C pre-processor failed...     ]]]
[[[ will try all known ABIs       ]]]
PR abi.default_abi=1
PR abi.sysv=1
PR abi.win64=2
```

**Comment by shawnlaffan** [comment]
I just successfully installed FFI::Platypus on a Mac M1 machine using libffi 3.4.4 from homebrew.  

Possibly it is the same underlying issue as for #374 

Perhaps https://github.com/PerlFFI/Alien-FFI/pull/29 should be applied to M1 macs as well?

**Comment by plicease** [comment]
It does seem to work now with 3.4.4

```
PR abi.sysv=1
PR abi.win64=2
PR abi.default_abi=1
```
