### ISSUE TITLE
libffi 3.4.3 may break Platypus on Linux ARM64

### ISSUE THREAD

**Issue by plicease** [PerlFFI/FFI-Platypus#374]
Doing a share install of Alien::FFI with this version of libffi seemed to cause some of the tests to fail.  I am pretty sure that I had previously installed with the system libffi, which definitely does work, so I am not sure if older versions of libffi also break Platypus.  This version seems to work just fine on macOS ARM64.

**Comment by AdrianBunk** [comment]
@plicease FYI, this does not seem to be specific to Platypus: https://bugs.debian.org/1021735

**Comment by plicease** [comment]
@AdrianBunk thanks, I think the right thing to do is block share installs of 3.4.3 in Alien::FFI for Linux+Arm64, and hope the next version fixes this.

**Comment by plicease** [comment]
I've released a version of Alien::FFI 0.26 which will block 3.4.3.  I will leave this ticket open for now and we can close it if this is resolved in the new version of libffi, or if we can patch it.

**Comment by plicease** [comment]
See also this ticket https://github.com/libffi/libffi/issues/744

**Comment by plicease** [comment]
Appears to be fixed in libffi 3.4.4.
