### ISSUE TITLE
Doc: add hint about using deferred execution to call free() to FFI::Platypus::Memory

### ISSUE THREAD

**Issue by zmughal** [PerlFFI/FFI-Platypus#378]
```perl
use Feature::Compat::Defer;
use FFI::Platypus::Memory qw(malloc free);

sub run {
  my $ptr = malloc(64);
  defer { free($ptr); }

  my $data = do_something($ptr);

  # do not need to place `free($ptr)` here as it will run through `defer`

  return $data;
}
```

See:

- `Feature::Compat::Defer`,
- `Scope::OnExit`,
- `Scope::Guard`, &
- more [here](https://github.com/zmughal-experiment/perl-parsing-panoply/blob/aaed580ee6140a4f93943a752ced1005d70472ba/NOTES.md#defer-running).

**Comment by plicease** [comment]
Thanks for writing this down, I put some copy into #384 relating to this.
